namespace SCH.Models.Auth.Enums
{
    /// <summary>
    /// Indicates how a refresh token was generated
    /// </summary>
    public enum RefreshTokenGeneratedBy
    {
        /// <summary>
        /// Token generated by username/password authentication
        /// </summary>
        UsernamePassword = 1,

        /// <summary>
        /// Token generated by refreshing an existing refresh token
        /// </summary>
        RefreshToken = 2
    }
}



